In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\shriy\\Downloads\\Book 3(Sheet1).csv")
df

,index,Order ID,Cust ID,Gender,Age,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1000000.0,Women,44,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2000000.0,Women,29,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,2000000.0,Women,67,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7000000.0,Women,20,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9000000.0,Women,62,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,5000000.0,Men,60,Delivered,Flipkart,J0083-KR-XL,kurta,XL,1,INR,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,5000000.0,Men,34,Delivered,Myntra,J0010-LCD-S,Set,S,1,INR,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,4000000.0,Men,29,Delivered,Amazon,SET398-KR-PP-L,Set,L,1,INR,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1000000.0,Men,46,Delivered,Amazon,JNE3568-KR-M,kurta,M,1,INR,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,5000000.0,Men,36,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,1,INR,791,WARANGAL,TELANGANA,506001,IN,False

In [6]:
df.columns=df.columns.str.replace(' ','_')

In [7]:
df.columns

Index(['index', 'Order_ID', 'Cust_ID', 'Gender', 'Age', 'Status', 'Channel_',
       'SKU', 'Category', 'Size', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'B2B'],
      dtype='object')

In [12]:
df=df.rename(columns={'Channel_':'Channel','ship-city':'ship_city','ship-state':'ship_state','ship-postal-code':'ship_postal_code',
                      'ship-country':'ship_country'})

In [14]:
df.columns

Index(['index', 'Order_ID', 'Cust_ID', 'Gender', 'Age', 'Status', 'Channel',
       'SKU', 'Category', 'Size', 'Qty', 'currency', 'Amount', 'ship_city',
       'ship_state', 'ship_postal_code', 'ship_country', 'B2B', 'age_group'],
      dtype='object')

In [15]:
#create a age group column
labels=['young_adult','adult','middle_aged','senior']
df['age_group']=pd.qcut(df['Age'],q=4,labels=labels)

In [16]:
df[['Age','age_group']].head(10)

   Age    age_group
0   44  middle_aged
1   29        adult
2   67       senior
3   20  young_adult
4   62       senior
5   49       senior
6   23  young_adult
7   70       senior
8   75       senior
9   43  middle_aged

In [17]:
df.isnull().sum()

index               0
Order_ID            0
Cust_ID             0
Gender              0
Age                 0
Status              0
Channel             0
SKU                 0
Category            0
Size                0
Qty                 0
currency            0
Amount              0
ship_city           0
ship_state          0
ship_postal_code    0
ship_country        0
B2B                 0
age_group           0
dtype: int64

In [18]:
df.describe()

             index       Cust_ID           Age        Amount  ship_postal_code
count  31047.00000  3.104700e+04  31047.000000  31047.000000      31047.000000
mean   15524.00000  4.937500e+06     39.496570    682.074822     460474.587206
std     8962.64124  2.925763e+06     15.117233    268.582173     198116.733009
min        1.00000  8.950000e+02     18.000000    229.000000     110001.000000
25%     7762.50000  2.000000e+06     28.000000    486.000000     313001.000000
50%    15524.00000  5.000000e+06     37.000000    646.000000     500028.000000
75%    23285.50000  7.000000e+06     47.000000    794.000000     600040.000000
max    31047.00000  1.000000e+07     78.000000   3036.000000     855117.000000

In [19]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:password@localhost/vrindastore")

In [20]:
df.to_sql(name="clothes", con=engine, if_exists="replace", index=False)

31047

In [21]:
result = pd.read_sql("SELECT * FROM clothes limit 5 ", con=engine)
print(result)

   index             Order_ID    Cust_ID Gender  Age     Status Channel  \
0      1  171-1029312-3038738  1000000.0  Women   44  Delivered  Myntra
1      2  405-2183842-2225946  2000000.0  Women   29  Delivered    Ajio
2      3  171-1641533-8921966  2000000.0  Women   67  Delivered  Myntra
3      4  404-7490807-6300351  7000000.0  Women   20  Delivered  Amazon
4      5  403-9293516-4577154  9000000.0  Women   62  Delivered  Myntra

                       SKU Category Size Qty currency  Amount  ship_city  \
0  JNE1233-BLUE-KR-031-XXL    kurta  XXL   1      INR     376     MOHALI
1           SET414-KR-NP-L      Set    L   1      INR    1449   GURUGRAM
2           SET261-KR-PP-S      Set    S   1      INR     453    KOLKATA
3           SET110-KR-PP-M      Set    M   1      INR     729  THANJAVUR
4         JNE2294-KR-A-XXL    kurta  XXL   1      INR     544   GURUGRAM

    ship_state  ship_postal_code ship_country  B2B    age_group
0       PUNJAB            140301           IN    0  middle_aged
1      HARYANA            122002           IN    0        adult
2  WEST BENGAL            700029           IN    0       senior
3   TAMIL NADU            613007           IN    0  young_adult
4      HARYANA            122001           IN    0       senior